var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,c){a.raw=c;return a};$jscomp.arrayIteratorImpl=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):$jscomp.arrayIterator(a)};
$jscomp.arrayFromIterator=function(a){for(var c,b=[];!(c=a.next()).done;)b.push(c.value);return b};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};var is2player,isBlackBot=Math.floor(2*Math.random()),modal=document.getElementById("modal"),boardHistory=[],lightTileCol="#cfcfcf",darkTileCol="#614796",boardBorderCol="#3f3f3f",lightTheme=0==Math.floor(20*Math.random());
lightTheme&&(document.body.style.background="#d8a2cf",document.getElementById("modal-content").style.backgroundColor="rgba(60, 60, 60, 0.85)",lightTileCol="#fff",darkTileCol="#fcb8ea",boardBorderCol="#fff");document.getElementById("playbot").onclick=function(){hideModal();is2player=!1;isBlackBot&&setTimeout(MakeAiMove,200)};document.getElementById("2player").onclick=function(){hideModal();is2player=!0};
function hideModal(){lightTheme||(document.body.style.background="#221c25");modal.style.visibility="hidden";document.getElementById("modal-content").style.visibility="visible";document.getElementById("modal-content").classList.add("hide");setTimeout(function(){document.getElementById("modal-content").classList.remove("hide");document.getElementById("2player").style.display="none";document.getElementById("playbot").style.display="none";modal.style.visibility="visible";modal.style.display="none"},300)}
var canvas=document.getElementById("board");window.addEventListener("resize",resizeCanvas);function resizeCanvas(){canvas.width=Math.min(window.innerHeight,window.innerWidth);canvas.height=canvas.width;refresh()}GetBoardWasm=Module.cwrap("get_board","string",[null]);function GetBoard(){var a=GetBoardWasm().slice(0,64);isBlackBot&&(a=[].concat($jscomp.arrayFromIterable(a)).reverse().join(""));return a}AiMove=Module.cwrap("ai_move",null,["number"]);
UserMove=Module.cwrap("user_move","number",["number","number"]);GetSquares=Module.cwrap("get_squares",null,["number","number"]);Module.onRuntimeInitialized=onRuntimeInitialized;function onRuntimeInitialized(){Module.ccall("init_board",null,[null],[]);resizeCanvas();checkLoaded()}function refresh(){var a=GetBoard();DrawBoard(canvas,a)}var move=new Int8Array(2),isMoving=!1,depth=5,ply=1;
function movePiece(a,c){var b=a.getBoundingClientRect(),e=a.width/8,d=Math.floor((c.clientX-b.left)/e);c=Math.floor((c.clientY-b.top)/e);b=GetBoard()[8*c+d];if(ply%2==(b==b.toUpperCase())&&"."!=b){isMoving=!0;refresh();move[0]=8*c+d;isBlackBot&&(move[0]=63-move[0]);e=Module._malloc(20);var f=Module.HEAP32.subarray(e/4,e/4+5);GetSquares(move[0],e);isBlackBot&&(f=f.map(function(g){return 63-g}));DrawMove(a,b,f,d,c);Module._free(e)}else isMoving=!1,a.style.cursor="default",move[1]=8*c+d,isBlackBot&&
(move[1]=63-move[1]),d=UserMove(move[0],move[1]),requestAnimationFrame(refresh),d&&(ply++,endGame()||is2player||(a.style.cursor="wait",setTimeout(MakeAiMove,30)))}function boardCursor(a,c){var b=a.getBoundingClientRect(),e=a.width/8,d=Math.floor((c.clientX-b.left)/e);c=Math.floor((c.clientY-b.top)/e);d=GetBoard()[8*c+d];isMoving||ply%2==(d==d.toUpperCase())&&"."!=d?a.style.cursor="pointer":a.style.cursor="default"}
function MakeAiMove(){var a=Date.now();ply++;AiMove(depth);300>Date.now()-a&&depth++;canvas.style.cursor="default";refresh();endGame()}
function endGame(){var a=[GetBoard(),boardHistory[3],boardHistory[7]].reduce(function(c,b,e,d){return b==d[0]});if(Module.ccall("is_mainboard_terminal","number",[null],[])||a)return refresh(),setTimeout(function(){var c=Module.ccall("score_mainboard","number",[null],[]),b=document.createElement("p"),e=document.createElement("button");e.innerHTML="play again";document.getElementById("modal-content").appendChild(b);document.getElementById("modal-content").appendChild(e);modal.style.display="block";
if(100==c){b.innerHTML="White Wins!";var d="#000";c="#ff7dbe"}else-100==c?(b.innerHTML="Black Wins!",d="#fff",c="#6832a8"):(b.innerHTML="Draw!",d="#dcdcdc",c="#595fa5");document.getElementById("modal-content").style="background-color: "+c+"; margin: 10% auto; color: "+d+";";b.style="font-size: 60px;";e.classList.add("button-small");e.onclick=function(){location.reload()}},0),!0;boardHistory.push(GetBoard());boardHistory=boardHistory.slice(0,8);return!1}
canvas.addEventListener("mousedown",function(a){movePiece(canvas,a)});canvas.addEventListener("mousemove",function(a){boardCursor(canvas,a)});var wp=new Image;wp.src="/img/pawnwhite.png";var bp=new Image;bp.src="/img/pawnblack.png";var wk=new Image;wk.src="/img/kingwhite.png";var bk=new Image;bk.src="/img/kingblack.png";function checkLoaded(){wp.complete&&wp.complete&&bp.complete&&wk.complete&&bk.complete?refresh():setTimeout(checkLoaded,50)}
function DrawBoard(a,c){var b=a.getContext("2d"),e=a.width,d=a.height;b.fillStyle=lightTileCol;b.fillRect(0,0,e,d);nRow=nCol=8;e/=nCol;d/=nRow;for(var f=0;f<nRow;++f)for(var g=0;g<nCol;++g){0==g%2&&(b.fillStyle=darkTileCol,b.fillRect(g*e+(f%2?0:e),f*d,e,d));var h=c[8*f+g];"."!=h&&DrawImage(h,b,g*e,f*d,e,d)}b.strokeStyle=boardBorderCol;b.lineWidth="5";b.beginPath();b.rect(0,0,a.width,a.height);b.stroke();b.strokeStyle="#000"}
function DrawImage(a,c,b,e,d,f){"p"==a?c.drawImage(bp,b,e,d,f):"P"==a?c.drawImage(wp,b,e,d,f):"k"==a?c.drawImage(bk,b,e,d,f):"K"==a&&c.drawImage(wk,b,e,d,f)}
function DrawMove(a,c,b,e,d){var f=a.getContext("2d");a=a.width/8;f.lineWidth="3";f.fillStyle="#241430";f.fillRect(e*a,d*a,a,a);DrawImage(c,f,e*a,d*a,a,a);f.beginPath();f.rect(e*a,d*a,a,a);f.stroke();for(i=0;5>i;i++)-1!=b[i]&&(e=b[i]%8,d=Math.floor(b[i]/8),f.beginPath(),f.rect(e*a,d*a,a,a),f.stroke(),f.globalAlpha=.2,f.fillStyle="#fc03ec",f.fillRect(e*a,d*a,a,a),f.globalAlpha=1)};
